### ISSUE TITLE
Gitmodules - fatal clone failed

### ISSUE THREAD

**Issue by StellaCassandra** [ucb-bar/midas-top-release#2]
Please query replace **git@github.com:** with **https://github.com/** in .gitmodules.

platforms/zynq/ also carries this issue in [midas-zynq](https://github.com/ucb-bar/midas-zynq):
[submodule "zc706_MIG/fpga-images-zc706"]
	path = zc706_MIG/fpga-images-zc706
url = git@github.com:ucb-bar/fpga-images-zc706.git

**Comment by davidbiancolin** [comment]
Oops, forgot the submodule.
