### ISSUE TITLE
Reading performance counters

### ISSUE THREAD

**Issue by NovoDavid** [ucb-bar/midas-top-release#4]
What would be the best way to access performance counters, such as L1D misses or cycles? I am trying to directly read the CSRs from the midas_top_zynq interface. However, I'm not able to find the addresses of the corresponding performance counters.

Looking at the MidasTop-const.h file, I can see the addresses of pokeable target inputs but none peekable target output.

**Comment by donggyukim** [comment]
For RISC-V processors including rocketchip, we use Chris' counter microbenchmark to read hpmcounters:
https://github.com/ccelio/riscv-hpmcounters

If we want to read counter values through I/O ports, we need FIRRTL compiler passes to instrument the target design. This may be supported in the future.

**Comment by NovoDavid** [comment]
In my case, I'm using a tethered implementation of the rocketchip running on a zynq board. I thought that it would be possible to access to the CSRs registers from the ARM on the PS side running the HTIF. So far, I am not running Linux on my implementation but rather using the RISC-V Proxy Kernel. Can you then confirm that I won't be able to access the CSRs registers in the midas_top_zynq program in a similar way we can read the registers added with "attach"?

**Comment by donggyukim** [comment]
In bare metal or pk, you could access hpmcounters by calling functions like:
https://github.com/donggyukim/cs152-sp18-lab4/blob/master/benchmarks/common/syscalls.c#L46

**Comment by NovoDavid** [comment]
I'm still a bit confused. I'm using the rocket core version of midas_top_release, which includes the following performance counters:

> // event mappings set to match BOOM's event numbers.
>   csr.io.events(0) := mem_reg_valid && !take_pc_wb && (mem_ctrl.branch || mem_ctrl.jalr)
>   csr.io.events(1) := mem_reg_valid && !take_pc_wb && (mem_ctrl.branch || mem_ctrl.jalr) && mem_wrong_npc
>   csr.io.events(50) := mem_reg_valid && !take_pc_wb && mem_ctrl.jalr
>   csr.io.events(51) := mem_reg_valid && !take_pc_wb && mem_ctrl.jalr && mem_wrong_npc
>   csr.io.events(2) := wb_valid && csr.io.status.prv === PRV.U
>   csr.io.events(28) := mem_reg_valid && !take_pc_wb && (mem_ctrl.branch || mem_ctrl.jalr) && csr.io.status.prv === PRV.U
>   csr.io.events(29) := mem_reg_valid && !take_pc_wb && (mem_ctrl.branch || mem_ctrl.jalr) && mem_wrong_npc && csr.io.status.prv === PRV.U
>   csr.io.events(17) := take_pc_wb
> 
>   // hook up counter events
>   csr.io.events(3) := io.dmem.dc_miss // d$ miss
>   csr.io.events(4) := io.imem.ic_miss // i$ miss
>   csr.io.events(31) := io.dmem.req.fire()  // d$ accesses
>   csr.io.events(32) := io.imem.resp.fire() // i$ accesses
>   csr.io.events(33) := io.dmem.tlb_miss // DTLB miss
>   csr.io.events(34) := io.imem.tlb_miss // ITLB miss

Does this mean that if I want to enable the ITLB miss counter I need to read mhpmcounter34?
I am confused when I take a look at the instructions.scala file and I see that the highest mhpmcounter defined is mhpmcounter31. How can I know the addresses of the counters defined in the Rocket.scala file?

**Comment by donggyukim** [comment]
Sorry for the late answer. For background, I recommend Section 3.1.15 of Priv 1.9, which is also similar in Priv 1.10:
https://people.eecs.berkeley.edu/~krste/papers/riscv-privileged-v1.9.1.pdf

First of all, you need to define each event in RTL. The above code defines each event. (e.g. `csr.io.events(3) := io.dmem.dc_miss` maps the D cache miss to event 3.)

Next, you should set `hpmevent<n>` to map event `n` to `hpmcounter<n>`. In my case, it is done by pk as follows:
https://github.com/donggyukim/riscv-pk/blob/counters/machine/minit.c#L34

For example, `write_csr(mhpmevent3, 4);` sets event 3 (yeah, the value should be `1+n` as 0 means no event) to `hpmcounter3`.

Finally, you can read the D cache stats through `read_csr(hpmcounter3)`.

**Comment by NovoDavid** [comment]
Thanks a lot! Your explanation and pointers made it crystal clear.
