### ISSUE TITLE
Fail to implement on ZYBO-Z7-20

### ISSUE THREAD

**Issue by JeremieMelo** [ucb-bar/midas-top-release#5]
When I use Rocketchip1GExtMen and ZynqConfig, I cannot implement it on zybo-z7-20. I got the error that hardware resources are not enough to implement this design. So it only works on zc706?
fpga-zynq repo works fine on zybo-z7-20. Does that mean the extra hardware resources required for Strober is super large?

**Comment by davidbiancolin** [comment]
Closing this, but feel free to re-open [here](https://github.com/ucb-bar/midas-top).

They are quite large, since the current implementation uses a shadow scan chain, which effectively doubles the amount of state.
